namespace Nsnbc
{
    public enum ArtName
    {
        Null,
        Pixel,
        Exterior,
        Logo,
        ADVBar,
        SpeakerLeft,
        SpeakerRight,
        InteriorGood,
        InteriorTrezorOpen,
        InteriorTrezorClosed,
        InteriorDrizzleRain,
        Thunderbolt,
        Darkness,
        PictureDetail,
        Cog64,
        Najdi,
        Cestu,
        Ven,
        TrezorBackground,
        Key,
        FastForward128,
        FastForward128Disabled,
        YouFoundIt,
        PotemnelaChodba1,
        PotemnelaChodba2,
        PotemnelaChodba3,
        AkelaExplaining,
        AkelaThinking,
        AkelaExcited,
        AkelaNormal,
        
        
        // Postavy to be reversed
        TisikThinking,
        TisikAngry,
        TisikDetermined,
        TisikPointing,
        TisikPokrcRamen,
        TisikSpeaking,
        TisikStrach,
        VedatorPointing,
        VedatorSpeaking,
        VedatorStrach,
        VedatorThinking,
        SkokNormalni,
        SkokThinking,
        SkokNastvany,
        SkokMluvici,
        TripleFear,
        TripleHappy,
    }
}