using System.Diagnostics.CodeAnalysis;
using JetBrains.Annotations;

namespace Nsnbc
{
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    public enum ArtName
    {
        Null,
        [UsedImplicitly]
        Pixel,
        Exterior,
        Logo,
        ADVBar,
        SpeakerLeft,
        SpeakerRight,
        InteriorGood,
        InteriorTrezorOpen,
        InteriorTrezorClosed,
        InteriorDrizzleRain,
        Thunderbolt,
        Darkness,
        PictureDetail,
        Cog64,
        Najdi,
        NajdiEn,
        Cestu,
        CestuEn,
        Ven,
        VenEn,
        TrezorBackground,
        Key,
        FastForward128,
        FastForward128Disabled,
        YouFoundIt,
        YouFoundItEn,
        PotemnelaChodba1,
        PotemnelaChodba2,
        PotemnelaChodba3,
        AkelaExplaining,
        AkelaThinking,
        AkelaExcited,
        AkelaNormal,
        MainLogoCzech,
        MainLogoEnglish,
        Background1,
        PromoArt1Czech,
        PromoArt1English,
        FlagEn,
        FlagCz,
        Auto128Disabled,
        Auto128,
        
        // Guardroom
        Guardroom1,
        Guardroom1LockedGate,
        Guardroom2,
        Guardroom3,
        Lednicka,
        Obraz1,
        Obraz2,
        R1_G1_MinimapIcon,
        R1_G2_MinimapIcon,
        R1_G3_MinimapIcon,
        R1_G3_Hrnecek,
        R1_G3_Triska,
        R1_Led_Figurka,
        R1_Led_Led,
        R1_Led_Triska,
        R1_Minimap,
        R1_Table,
        R1_Table_Trisky,
        R1Bludiste,
        R1Fire,

        // Postavy to be reversed
        TisikThinking,
        TisikAngry,
        TisikDetermined,
        TisikPointing,
        TisikPokrcRamen,
        TisikSpeaking,
        TisikStrach,
        VedatorPointing,
        VedatorSpeaking,
        VedatorStrach,
        VedatorThinking,
        SkokNormalni,
        SkokThinking,
        SkokNastvany,
        SkokMluvici,
        TripleFear,
        TripleHappy,
        SlotQuestion,
        SlotBlank,
        SlotLoading,
        TurnAround128Disabled,
        TurnAround128,
        Left128,
        Left128Disabled,
        Right128,
        Right128Disabled,
        
        R1Balicek,
        R1Baterie,
        R1Disketa,
        R1Figurka,
        R1Hrnecek,
        R1HrnecekSVodou,
        R1PapirSeStavou,
        R1PrazdnyPapir,
        R1Triska,
        R1ZelenyKlic,
        R1HrnecekSHorkouVodou,
        R1Sirky
    }
}